apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: django-app  # Make sure this matches the labels in your "template metadata label" of deployment.yml file
  ports:
    - protocol: TCP
      port: 80  # External port of the host ec2
      targetPort: 8000  # Internal port of your application
  type: LoadBalancer



  # Before you apply a Service of type LoadBalancer, the associated Deployment should be up and running. 
  # The Service is responsible for directing traffic to the pods managed by the Deployment. 
  # If the Deployment is not yet created or if there are no running pods, the Service won't have any pods to direct traffic to, and the external IP/DNS of the Load Balancer won't be assigned.


# --- o/p ---
# service/chatbot-service   LoadBalancer   10.100.139.186   a8fe2d28e3f19415ab5607f7a9e8086a-1624399641.us-east-1.elb.amazonaws.com   80:31923/TCP   12s

# 80:31923/TCP: This part indicates how the ports are mapped:

# 80 on the host (external port)
# 31923 on the service (internal port)
# So, external traffic directed to port 80 of the ELB will be forwarded to port 31923 on the service, and from there, it will be forwarded to the pods.


